apiVersion: apps/v1
kind: Deployment
metadata:
  name: boomi-flow-runtime
  namespace: boomi-flow
spec:
  replicas: 2
  selector:
    matchLabels:
      app: boomi-flow-runtime
  template:
    metadata:
      labels:
        app: boomi-flow-runtime
    spec:
      containers:
      - name: flow
        image: boomi/flow:latest
        env:
        - name: BASE_URL
          valueFrom:
            configMapKeyRef:
              name: boomi-flow-config
              key: boomi-flow-runtime-lb
        - name: DATABASE_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: boomi-flow-secret
              key: DATABASE_CONNECTION_STRING
        - name: INSTALLATION_TOKEN
          valueFrom:
              secretKeyRef:
                name: boomi-flow-secret
                key: INSTALLATION_TOKEN     
        ports:
        - containerPort: 80
      restartPolicy: Always


